experiment:
  name: hammering_target
  seed: 1
  torch_deterministic: true
  device: cuda

environment:
  reward_divisor: 622.2
  material: hard
  min_air_steps: 5
  min_delta_fn: 20.0
  horizon: 500
  control_freq: 20
  joint_torque_limits:
    2: 25
    4: 25
  reward_mode: target
  target_pos: [0.0, 0.0]
  target_radius: 0.03
  target_height: 0.005

training:
  total_timesteps: 3000000
  learning_rate: 3.0e-4
  num_envs: 32
  num_steps: 1024
  vec_env_type: async
  anneal_lr: true
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 32
  update_epochs: 10
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.02
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null
  bound_coef: 0.001
  drop_gripper: true
  osc_kp: 150

logging:
  track: true
  wandb_project: tuli
  wandb_entity: null
  save_model: true
  num_checkpoints: 5
